//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic
    {
        public int PasNumber { get; set; }
        public string Forenames { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string SexCode { get; set; }
        public string HomeTelephoneNumber { get; set; }
    
        public virtual GpDetail GpDetail { get; set; }
        public virtual NextOfKin NextOfKin { get; set; }
    }
}
