//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GpDetail
    {
        public int PatientPasNumber { get; set; }
        public string GpCode { get; set; }
        public string GpSurname { get; set; }
        public string GpInitials { get; set; }
        public string GpPhone { get; set; }
    
        public virtual Basic Basic { get; set; }
    }
}
