//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NextOfKin
    {
        public int PatientPasNumber { get; set; }
        public string NokName { get; set; }
        public string NokRelationshipCode { get; set; }
        public string NokAddressLine1 { get; set; }
        public string NokAddressLine2 { get; set; }
        public string NokAddressLine3 { get; set; }
        public string NokAddressLine4 { get; set; }
        public string NokPostcode { get; set; }
    
        public virtual Basic Basic { get; set; }
    }
}
